version: "2"
services:
  app:
    container_name: kites-docsify
    restart: always
    image: kitesjs/docsify
    ports:
      - 3002:3000
    volumes:
      # home directory
      - /home/kites/docsify:/opt/kites-docsify
    environment:
      - NODE_ENV=production
      - GITWORKDIR=/opt/kites-docsify
      - express_static=/opt/kites-docsify/docs
